import { initSchema } from "./schema.js";
import { tripsRepo, usersRepo, savedPlacesRepo } from "./repositories.js";

export function runSeed() {
  console.log("[DB Seed] Starting database seeding...");
  initSchema();

  // 1. Seed Demo User
  let demoUser = usersRepo.findUserByEmail("demo@tripwise.ai");
  if (!demoUser) {
    demoUser = usersRepo.createUser({
      name: "Alex Traveler",
      email: "demo@tripwise.ai",
      passwordHash: "demo12345",
    });
    console.log("[DB Seed] Created demo user: demo@tripwise.ai");
  }

  // 2. Seed Kyoto Trip
  const kyotoId = "trip_seed_kyoto_odyssey";
  const kyotoTrip = tripsRepo.saveTrip({
    id: kyotoId,
    userId: demoUser.id,
    city: "San Francisco",
    destination: "Kyoto",
    budget: 2800,
    duration: 3,
    fromDate: "2026-10-10",
    toDate: "2026-10-13",
    travelStyle: "Culture",
    preferences: "Ancient shrines, matcha tea ceremonies, bamboo groves, serene zen gardens",
    imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&h=700&fit=crop",
    tripData: {
      budgetBreakdown: {
        flights: 980,
        hotels: 850,
        food: 420,
        transport: 180,
        activities: 250,
        shopping: 120,
      },
      tripHighlights: {
        flight: "ANA Flight NH007 • SFO → KIX",
        hotel: "Ryokan Gion Sano Kyoto",
        topRated: "Fushimi Inari Taisha",
        activities: 12,
        restaurants: 6,
        nearbyPlaces: ["Arashiyama Bamboo Grove", "Gion Historic District", "Kinkaku-ji Golden Pavilion", "Nijo Castle"],
        travelTips: [
          { category: "Timing", title: "Early Morning Torii Walk", description: "Arrive at Fushimi Inari at 07:30 AM before tourist crowds gather." },
          { category: "Transport", title: "ICOCA Transit Card", description: "Buy an ICOCA card at Kyoto Station for seamless subway and city bus tapping." },
          { category: "Food", title: "Matcha Sweets in Uji", description: "Try authentic Uji green tea parfait and roasted hojicha in historic teahouses." },
          { category: "Photography", title: "Bamboo Grove Sunbeams", description: "Shoot through towering bamboo stalks in Arashiyama during early morning hours." },
        ],
      },
      days: [
        {
          day: 1,
          title: "Historic Shrines & Gion Evening",
          activities: [
            {
              time: "08:30 AM",
              title: "Walk the Thousand Torii at Fushimi Inari",
              type: "Sightseeing",
              location: "Fushimi Ward, Kyoto",
              description: "Hike through thousands of bright vermilion torii gates winding up sacred Mount Inari.",
              duration: "2.5 Hours",
              cost: "Free",
              rating: 4.9,
              bookingRequired: false,
              bestTime: "Early Morning",
              additionalDetails: "Arrive at sunrise for tranquility and uninterrupted photography.",
              aiRecommendation: "Wear sturdy footwear; the upper mountain path is steep but rewarding.",
            },
            {
              time: "12:30 PM",
              title: "Traditional Kaiseki Lunch in Gion",
              type: "Dining",
              location: "Gion District, Kyoto",
              description: "Delight in seasonal multi-course Japanese dining celebrating regional ingredients.",
              duration: "1.5 Hours",
              cost: "$45",
              rating: 4.8,
              bookingRequired: true,
              bestTime: "Afternoon",
              additionalDetails: "Vegetarian and pescatarian options available with advance request.",
              aiRecommendation: "Reserve 3 days ahead for courtyard garden views.",
            },
            {
              time: "03:00 PM",
              title: "Kiyomizu-dera Wooden Stage & City Overlook",
              type: "Sightseeing",
              location: "Higashiyama, Kyoto",
              description: "Marvel at panoramic Kyoto views from this cliffside UNESCO World Heritage wooden temple.",
              duration: "2 Hours",
              cost: "$4",
              rating: 4.9,
              bookingRequired: false,
              bestTime: "Late Afternoon",
              additionalDetails: "Drink from Otowa Waterfall fountains for health and longevity.",
              aiRecommendation: "Sunset lighting reflects magically across the hillside forest.",
            },
            {
              time: "07:30 PM",
              title: "Pontocho Alley Izakaya Dinner",
              type: "Dining",
              location: "Pontocho Alley, Kamogawa",
              description: "Atmospheric lantern-lit dining alongside the tranquil Kamogawa riverbanks.",
              duration: "2 Hours",
              cost: "$50",
              rating: 4.7,
              bookingRequired: false,
              bestTime: "Evening",
              additionalDetails: "Summer terraces (Kawayuka) provide riverside evening breeze.",
              aiRecommendation: "Try local Kyoto craft beer and charcoal-grilled yakitori skewers.",
            },
          ],
        },
        {
          day: 2,
          title: "Arashiyama Bamboo & Golden Pavilion",
          activities: [
            {
              time: "09:00 AM",
              title: "Arashiyama Bamboo Grove Walk",
              type: "Sightseeing",
              location: "Arashiyama, Western Kyoto",
              description: "Wander through the soaring green stalks of Kyoto's world-renowned bamboo forest.",
              duration: "2 Hours",
              cost: "Free",
              rating: 4.8,
              bookingRequired: false,
              bestTime: "Morning",
              additionalDetails: "Continue directly into Tenryu-ji temple garden behind the grove.",
              aiRecommendation: "Catch the rustling sound of the bamboo stalks in the morning wind.",
            },
            {
              time: "01:00 PM",
              title: "Matcha Tea Tasting & Soba Noodles",
              type: "Dining",
              location: "Saga-Toriimoto",
              description: "Taste freshly handmade buckwheat soba paired with ceremonial Uji matcha tea.",
              duration: "1 Hour",
              cost: "$22",
              rating: 4.7,
              bookingRequired: false,
              bestTime: "Afternoon",
              additionalDetails: "Charming traditional wooden townhouse setting.",
              aiRecommendation: "Order the matcha parfait for dessert.",
            },
            {
              time: "03:00 PM",
              title: "Kinkaku-ji (The Golden Pavilion)",
              type: "Sightseeing",
              location: "Kita Ward, Kyoto",
              description: "Witness the iconic gold-leaf covered Zen temple shimmering across Mirror Pond.",
              duration: "1.5 Hours",
              cost: "$5",
              rating: 4.9,
              bookingRequired: false,
              bestTime: "Afternoon",
              additionalDetails: "Follow designated one-way path through moss gardens.",
              aiRecommendation: "Best photography spot is from the shore across Kyoko-chi pond.",
            },
            {
              time: "07:00 PM",
              title: "Nishiki Market Culinary Tour",
              type: "Dining",
              location: "Nakagyo Ward, Kyoto",
              description: "Sample skewered wagyu, takoyaki, pickled vegetables, and mochi sweets.",
              duration: "2 Hours",
              cost: "$35",
              rating: 4.8,
              bookingRequired: false,
              bestTime: "Evening",
              additionalDetails: "Kyoto's 400-year-old food street known as 'Kyoto's Kitchen'.",
              aiRecommendation: "Carry cash for vendor stalls.",
            },
          ],
        },
        {
          day: 3,
          title: "Philosopher's Path & Zen Meditation",
          activities: [
            {
              time: "09:30 AM",
              title: "Philosopher's Path Canal Walk",
              type: "Sightseeing",
              location: "Sakyo Ward, Kyoto",
              description: "Scenic stone path following a cherry-tree lined canal between Ginkaku-ji and Nanzen-ji.",
              duration: "2 Hours",
              cost: "Free",
              rating: 4.7,
              bookingRequired: false,
              bestTime: "Morning",
              additionalDetails: "Stop by artisan pottery craft workshops along the route.",
              aiRecommendation: "Quiet morning hours offer pure meditative serenity.",
            },
            {
              time: "12:30 PM",
              title: "Shojin Ryori (Zen Buddhist Lunch)",
              type: "Dining",
              location: "Nanzen-ji Temple Grounds",
              description: "Authentic temple tofu and seasonal vegetarian gastronomy practiced by Zen monks.",
              duration: "1.5 Hours",
              cost: "$38",
              rating: 4.8,
              bookingRequired: true,
              bestTime: "Afternoon",
              additionalDetails: "Famous Yudofu (simmered tofu in kelp broth).",
              aiRecommendation: "Ask for a tatami table overlooking the Japanese rock garden.",
            },
            {
              time: "03:00 PM",
              title: "Nijo Castle Nightingales & Gardens",
              type: "Sightseeing",
              location: "Nijo Castle, Kyoto",
              description: "Explore the historic samurai shogun fortress with squeaking 'nightingale' alarm floors.",
              duration: "2 Hours",
              cost: "$10",
              rating: 4.8,
              bookingRequired: false,
              bestTime: "Afternoon",
              additionalDetails: "Audio guide available in multiple languages.",
              aiRecommendation: "Look closely at the gold leaf wall paintings inside Ninomaru Palace.",
            },
            {
              time: "07:30 PM",
              title: "Farewell Skyline Dinner overlooking Kyoto Tower",
              type: "Dining",
              location: "Shimogyo Ward, Kyoto",
              description: "Celebrate the conclusion of your trip with panoramic views and regional fusion cuisine.",
              duration: "2 Hours",
              cost: "$65",
              rating: 4.9,
              bookingRequired: true,
              bestTime: "Evening",
              additionalDetails: "Smart casual dress code.",
              aiRecommendation: "Toast with Kyoto plum wine as the city illuminates below.",
            },
          ],
        },
      ],
    },
  });

  // 3. Seed saved places for Kyoto
  savedPlacesRepo.savePlace({
    tripId: kyotoId,
    userId: demoUser.id,
    name: "Fushimi Inari Taisha",
    category: "Shrine",
    rating: 4.9,
    address: "68 Fukakusa Yabunouchicho, Fushimi Ward, Kyoto",
    imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200",
  });

  savedPlacesRepo.savePlace({
    tripId: kyotoId,
    userId: demoUser.id,
    name: "Gion Historic Quarter",
    category: "Historic District",
    rating: 4.8,
    address: "Higashiyama Ward, Kyoto",
    imageUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200",
  });

  // 4. Seed Paris Art & Romance Trip
  const parisId = "trip_seed_paris_elegance";
  const parisTrip = tripsRepo.saveTrip({
    id: parisId,
    userId: demoUser.id,
    city: "New York",
    destination: "Paris",
    budget: 3400,
    duration: 4,
    fromDate: "2026-09-15",
    toDate: "2026-09-19",
    travelStyle: "City Exploration",
    preferences: "Impressionist art, Parisian cafes, Eiffel Tower golden hour, historic bakeries",
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&h=700&fit=crop",
    tripData: {
      budgetBreakdown: {
        flights: 1100,
        hotels: 1200,
        food: 550,
        transport: 180,
        activities: 250,
        shopping: 120,
      },
      tripHighlights: {
        flight: "Air France AF007 • JFK → CDG",
        hotel: "Hôtel Le Relais Saint-Germain",
        topRated: "Musée d'Orsay & Louvre",
        activities: 16,
        restaurants: 8,
        nearbyPlaces: ["Eiffel Tower", "Louvre Museum", "Montmartre & Sacré-Cœur", "Seine River Cruise"],
        travelTips: [
          { category: "Timing", title: "Louvre Evening Hours", description: "Visit the Louvre on Friday evenings for quieter galleries and lit glass pyramids." },
          { category: "Transport", title: "Navigo Easy Metro Card", description: "Use contactless Navigo Easy card for seamless Parisian metro and RER travel." },
          { category: "Food", title: "Fresh Croissant Etiquette", description: "Always ask for a 'croissant au beurre' at artisanal neighborhood boulangeries." },
          { category: "Photography", title: "Trocadéro Sunrise", description: "Best unobstructed view of the Eiffel Tower is from the Trocadéro terrace at sunrise." },
        ],
      },
      days: [
        {
          day: 1,
          title: "Iconic Seine, Louvre & Palais Garnier",
          activities: [
            {
              time: "09:00 AM",
              title: "Louvre Museum Masterpieces",
              type: "Sightseeing",
              location: "Rue de Rivoli, Paris",
              description: "Marvel at the Mona Lisa, Venus de Milo, and Winged Victory of Samothrace.",
              duration: "3 Hours",
              cost: "$22",
              rating: 4.8,
              bookingRequired: true,
              bestTime: "Morning",
              additionalDetails: "Timed entry tickets booked online avoid 2-hour queue lines.",
              aiRecommendation: "Enter through the Carrousel du Louvre underground entrance to skip surface crowds.",
            },
            {
              time: "01:00 PM",
              title: "Bistro Lunch at Café de Flore",
              type: "Dining",
              location: "Saint-Germain-des-Prés, Paris",
              description: "Classic Parisian croque-monsieur and cafe au lait in this historic existentialist writers' haunt.",
              duration: "1.5 Hours",
              cost: "$35",
              rating: 4.6,
              bookingRequired: false,
              bestTime: "Afternoon",
              additionalDetails: "Outdoor terrace tables are ideal for people watching.",
              aiRecommendation: "Order the house hot chocolate served in porcelain pitchers.",
            },
            {
              time: "03:30 PM",
              title: "Tuileries Garden & Place de la Concorde",
              type: "Sightseeing",
              location: "1st Arrondissement, Paris",
              description: "Stroll along the historic gravel pathways between fountains and classical French statues.",
              duration: "1.5 Hours",
              cost: "Free",
              rating: 4.7,
              bookingRequired: false,
              bestTime: "Afternoon",
              additionalDetails: "Green chairs around the central fountain are free to pull up anywhere.",
              aiRecommendation: "Pick up macarons from nearby Angelina tea salon to enjoy in the park.",
            },
            {
              time: "07:30 PM",
              title: "Illuminated Seine River Cruise",
              type: "Sightseeing",
              location: "Pont Neuf, Paris",
              description: "Glide beneath historic bridges as Notre-Dame and the Eiffel Tower sparkle after dusk.",
              duration: "1.5 Hours",
              cost: "$25",
              rating: 4.9,
              bookingRequired: true,
              bestTime: "Evening",
              additionalDetails: "Top open deck can get breezy; bring a light scarf or jacket.",
              aiRecommendation: "Board 30 minutes before on-the-hour to catch the Eiffel Tower 5-minute sparkle show.",
            },
          ],
        },
        {
          day: 2,
          title: "Montmartre Artistry & Sacré-Cœur Panoramas",
          activities: [
            {
              time: "09:30 AM",
              title: "Sacré-Cœur Dome Climb",
              type: "Sightseeing",
              location: "Montmartre, Paris",
              description: "Climb the 300 steps of the white stone basilica for the highest panoramic view of all Paris.",
              duration: "2 Hours",
              cost: "$8",
              rating: 4.8,
              bookingRequired: false,
              bestTime: "Morning",
              additionalDetails: "Take the Montmartre funicular using a standard metro ticket.",
              aiRecommendation: "Visit the crypt inside before heading up to the panoramic dome.",
            },
            {
              time: "12:30 PM",
              title: "Artisanal Lunch on Rue des Abbesses",
              type: "Dining",
              location: "18th Arrondissement, Paris",
              description: "Enjoy regional galettes, organic cider, and fresh salad in an intimate bohemian Montmartre cafe.",
              duration: "1.5 Hours",
              cost: "$28",
              rating: 4.7,
              bookingRequired: false,
              bestTime: "Afternoon",
              additionalDetails: "Gluten-free buckwheat crêpes made to order.",
              aiRecommendation: "Try the salted caramel crêpe for dessert.",
            },
            {
              time: "03:00 PM",
              title: "Musée d'Orsay Impressionist Treasures",
              type: "Sightseeing",
              location: "7th Arrondissement, Paris",
              description: "Housed in a grand Beaux-Arts railway station, see Monet, Van Gogh, Renoir, and Degas.",
              duration: "2.5 Hours",
              cost: "$18",
              rating: 4.9,
              bookingRequired: true,
              bestTime: "Afternoon",
              additionalDetails: "Famous giant clock face provides a silhouetted window over Montmartre.",
              aiRecommendation: "Start on the 5th floor Impressionist gallery before descending to sculptures.",
            },
            {
              time: "07:30 PM",
              title: "Dinner in Le Marais Historic Quarter",
              type: "Dining",
              location: "4th Arrondissement, Paris",
              description: "Contemporary French bistronomy featuring seasonal farmer ingredients in 17th-century masonry.",
              duration: "2 Hours",
              cost: "$60",
              rating: 4.8,
              bookingRequired: true,
              bestTime: "Evening",
              additionalDetails: "Exceptional biodynamic wine pairings available.",
              aiRecommendation: "Reservations 1 week in advance strongly recommended.",
            },
          ],
        },
      ],
    },
  });

  // 5. Seed Seoul Futuristic Exploration Trip
  const seoulId = "trip_seed_seoul_pulse";
  const seoulTrip = tripsRepo.saveTrip({
    id: seoulId,
    userId: demoUser.id,
    city: "London",
    destination: "Seoul",
    budget: 2900,
    duration: 3,
    fromDate: "2026-11-01",
    toDate: "2026-11-04",
    travelStyle: "Food & Culinary",
    preferences: "K-food night markets, Hanok villages, futuristic architecture, Dongdaemun design",
    imageUrl: "https://images.unsplash.com/photo-1538485399081-7191377e8241?w=1200&h=700&fit=crop",
    tripData: {
      budgetBreakdown: {
        flights: 1050,
        hotels: 800,
        food: 450,
        transport: 150,
        activities: 250,
        shopping: 200,
      },
      tripHighlights: {
        flight: "Korean Air KE908 • LHR → ICN",
        hotel: "Signiel Seoul / Lotte World Tower",
        topRated: "Gyeongbokgung Palace & Bukchon",
        activities: 12,
        restaurants: 6,
        nearbyPlaces: ["Gyeongbokgung Palace", "Bukchon Hanok Village", "N Seoul Tower", "Gwangjang Market"],
        travelTips: [
          { category: "Timing", title: "Royal Guard Changing Ceremony", description: "Catch the ceremonial guard change at Gyeongbokgung daily at 10:00 AM and 2:00 PM." },
          { category: "Transport", title: "T-Money Card", description: "Purchase and recharge a T-money card at any convenience store for all subways, buses, and taxis." },
          { category: "Food", title: "Gwangjang Night Market Bindaetteok", description: "Try freshly ground mung bean pancakes and hand-cut kalguksu noodles." },
          { category: "Culture", title: "Free Palace Entry in Hanbok", description: "Renting traditional Hanbok attire gives you complimentary admission to all five royal palaces." },
        ],
      },
      days: [
        {
          day: 1,
          title: "Palaces, Hanoks & Street Food Feast",
          activities: [
            {
              time: "09:30 AM",
              title: "Gyeongbokgung Palace & Secret Gardens",
              type: "Sightseeing",
              location: "Jongno-gu, Seoul",
              description: "The grandest of the Joseon dynasty palaces with ornate throne halls and reflection pavilions.",
              duration: "2.5 Hours",
              cost: "$3",
              rating: 4.9,
              bookingRequired: false,
              bestTime: "Morning",
              additionalDetails: "Closed on Tuesdays.",
              aiRecommendation: "Rent a Hanbok nearby for free entrance and unforgettable photo memories.",
            },
            {
              time: "12:30 PM",
              title: "Street Food Feast at Gwangjang Market",
              type: "Dining",
              location: "Dongdaemun, Seoul",
              description: "Seoul's oldest century-old traditional food market bustling with sizzling griddles.",
              duration: "1.5 Hours",
              cost: "$15",
              rating: 4.8,
              bookingRequired: false,
              bestTime: "Lunch",
              additionalDetails: "Cash or T-money accepted at most central stalls.",
              aiRecommendation: "Order Mayak kimbap and crispy bindaetteok with raw onion vinegar dipping sauce.",
            },
            {
              time: "03:00 PM",
              title: "Bukchon Hanok Village Heritage Walk",
              type: "Sightseeing",
              location: "Bukchon, Seoul",
              description: "Wander picturesque alleys preserved with traditional tiled-roof wooden Korean homes.",
              duration: "2 Hours",
              cost: "Free",
              rating: 4.7,
              bookingRequired: false,
              bestTime: "Afternoon",
              additionalDetails: "This is a quiet residential area; observe whisper zones and signs.",
              aiRecommendation: "Visit a traditional Hanok teahouse for omija (five-flavor berry) tea.",
            },
            {
              time: "07:30 PM",
              title: "Korean BBQ & Makgeolli in Hongdae",
              type: "Dining",
              location: "Hongdae, Seoul",
              description: "Charcoal tabletop grilled Hanwoo beef and pork belly with kimchi and chilled draft makgeolli.",
              duration: "2 Hours",
              cost: "$35",
              rating: 4.9,
              bookingRequired: false,
              bestTime: "Evening",
              additionalDetails: "Staff will demonstrate the proper way to assemble perilla leaf ssam wraps.",
              aiRecommendation: "Finish with cold naengmyeon noodles to balance the grilled feast.",
            },
          ],
        },
      ],
    },
  });

  console.log("[DB Seed] Seeded Kyoto (" + kyotoTrip.id + "), Paris (" + parisTrip.id + "), Seoul (" + seoulTrip.id + ")");
  console.log("[DB Seed] Seeding completed successfully!");
}

// Allow direct execution: node server/src/db/seed.js
if (process.argv[1] && process.argv[1].endsWith("seed.js")) {
  runSeed();
}
